#index:
#    path: /
#    controller: App\Controller\DefaultController::index
deletecomment:
    path: admin/comments/delete/{id}
    controller: App\Controller\AdminController::deletecomment

# /app/config/routes.yaml
captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"    